// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptDirectTransfer(arg1) {
  return window['go']['main']['App']['AcceptDirectTransfer'](arg1);
}

export function CancelDirectSession(arg1) {
  return window['go']['main']['App']['CancelDirectSession'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearTransferHistory() {
  return window['go']['main']['App']['ClearTransferHistory']();
}

export function CopyTransferLink(arg1) {
  return window['go']['main']['App']['CopyTransferLink'](arg1);
}

export function CreateCloudPubTransfer(arg1) {
  return window['go']['main']['App']['CreateCloudPubTransfer'](arg1);
}

export function CreateDirectTransfer(arg1) {
  return window['go']['main']['App']['CreateDirectTransfer'](arg1);
}

export function CreateInternetTransfer(arg1) {
  return window['go']['main']['App']['CreateInternetTransfer'](arg1);
}

export function CreateTransfer(arg1) {
  return window['go']['main']['App']['CreateTransfer'](arg1);
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function GetAvailableNetworkEndpoints() {
  return window['go']['main']['App']['GetAvailableNetworkEndpoints']();
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetRecommendedRelayURL() {
  return window['go']['main']['App']['GetRecommendedRelayURL']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTransfer(arg1) {
  return window['go']['main']['App']['GetTransfer'](arg1);
}

export function GetTransferLimits() {
  return window['go']['main']['App']['GetTransferLimits']();
}

export function GetTransferQRCode(arg1) {
  return window['go']['main']['App']['GetTransferQRCode'](arg1);
}

export function ListActiveTransfers() {
  return window['go']['main']['App']['ListActiveTransfers']();
}

export function ListIncomingTransfers() {
  return window['go']['main']['App']['ListIncomingTransfers']();
}

export function ListTransferHistory(arg1) {
  return window['go']['main']['App']['ListTransferHistory'](arg1);
}

export function RevealTransferSourceFile(arg1) {
  return window['go']['main']['App']['RevealTransferSourceFile'](arg1);
}

export function SaveTransferQRCode(arg1) {
  return window['go']['main']['App']['SaveTransferQRCode'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFilesAsZip() {
  return window['go']['main']['App']['SelectFilesAsZip']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
