// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {main} from '../models';

export function AcceptDirectTransfer(arg1:string):Promise<application.IncomingTransferDto>;

export function CancelDirectSession(arg1:string):Promise<void>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearTransferHistory():Promise<void>;

export function CopyTransferLink(arg1:string):Promise<void>;

export function CreateCloudPubTransfer(arg1:main.CreateCloudPubTransferRequest):Promise<application.TransferDetails>;

export function CreateDirectTransfer(arg1:application.CreateDirectTransferRequest):Promise<application.TransferDetails>;

export function CreateInternetTransfer(arg1:application.CreateInternetTransferRequest):Promise<application.TransferDetails>;

export function CreateTransfer(arg1:application.CreateTransferRequest):Promise<application.TransferDetails>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function GetAvailableNetworkEndpoints():Promise<any>;

export function GetDiagnostics():Promise<main.DiagnosticsDto>;

export function GetRecommendedRelayURL():Promise<main.RelayRecommendationDto>;

export function GetSettings():Promise<main.SettingsDto>;

export function GetTransfer(arg1:string):Promise<application.TransferDetails>;

export function GetTransferLimits():Promise<main.TransferLimitsDto>;

export function GetTransferQRCode(arg1:string):Promise<main.QrCodeDto>;

export function ListActiveTransfers():Promise<Array<application.TransferDetails>>;

export function ListIncomingTransfers():Promise<Array<application.IncomingTransferDto>>;

export function ListTransferHistory(arg1:any):Promise<Array<application.TransferDetails>>;

export function RevealTransferSourceFile(arg1:string):Promise<void>;

export function SaveTransferQRCode(arg1:string):Promise<main.SaveResultDto>;

export function SelectFile():Promise<main.FileSelectionDto>;

export function SelectFilesAsZip():Promise<main.FileSelectionDto>;

export function UpdateSettings(arg1:main.SettingsDto):Promise<main.SettingsDto>;
